# Generated by Django 4.2.11 on 2026-04-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('schema_markup', models.JSONField(blank=True, help_text='JSON-LD schema markup', null=True)),
                ('index_page', models.BooleanField(default=True, help_text='Should search engines index this page?')),
                ('follow_links', models.BooleanField(default=True, help_text='Should search engines follow links on this page?')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(help_text='HTML content for the blog post')),
                ('image', models.ImageField(upload_to='articles/')),
                ('author', models.CharField(default='Dr. Ulhas Sonar', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('category_color', models.CharField(default='bg-blue-100 text-blue-600', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('schema_markup', models.JSONField(blank=True, help_text='JSON-LD schema markup', null=True)),
                ('index_page', models.BooleanField(default=True, help_text='Should search engines index this page?')),
                ('follow_links', models.BooleanField(default=True, help_text='Should search engines follow links on this page?')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=100)),
                ('items', models.JSONField(default=list, help_text='List of features or highlights')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots_txt', models.TextField(default='User-agent: *\nAllow: /')),
                ('header_scripts', models.TextField(blank=True, help_text='GSC, Google Analytics, etc.')),
                ('footer_scripts', models.TextField(blank=True)),
                ('internal_linking_rules', models.JSONField(default=dict, help_text='Keyword to URL mapping')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('HI', 'Hindi')], max_length=10)),
                ('value', models.JSONField(help_text='The translated text or JSON object')),
            ],
            options={
                'unique_together': {('key', 'language')},
            },
        ),
    ]
