# Generated by Django 4.2.11 on 2026-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='e.g., /old-page/', max_length=255, unique=True)),
                ('new_path', models.CharField(blank=True, help_text='Leave blank for 410/451', max_length=255, null=True)),
                ('status_code', models.IntegerField(choices=[(301, '301 - Permanent Redirect'), (302, '302 - Temporary Redirect'), (410, '410 - Gone (Deleted)'), (451, '451 - Unavailable for Legal Reasons')], default=301)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='h1_title',
            field=models.CharField(blank=True, help_text='Optional: Override the default H1 title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the main image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='h1_title',
            field=models.CharField(blank=True, help_text='Optional: Override the default H1 title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for the main image', max_length=255, null=True),
        ),
    ]
