# Generated by Django 4.2.11 on 2026-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='items',
            field=models.JSONField(default=list, help_text='Enter a JSON list, e.g., ["Feature 1", "Feature 2"]'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='internal_linking_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Enter a JSON object, e.g., {"Knee Pain": "/services/knee-pain"}'),
        ),
    ]
