# Generated by Django 4.2.11 on 2026-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('MedicalBusiness', 'Medical Business / Local Business'), ('FAQPage', 'FAQ Page'), ('BreadcrumbList', 'Breadcrumbs'), ('None', 'Custom / None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('MedicalBusiness', 'Medical Business / Local Business'), ('FAQPage', 'FAQ Page'), ('BreadcrumbList', 'Breadcrumbs'), ('None', 'Custom / None')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's absolute URL", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customredirect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's absolute URL", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
