# Generated by hand to convert tables to utf8mb4 collation for phonetic symbols / unicode support

from django.db import migrations

def convert_tables_to_utf8mb4(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Change database defaults
            cursor.execute("ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
            
            # Convert each table
            cursor.execute("ALTER TABLE api_article CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
            cursor.execute("ALTER TABLE api_service CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
            cursor.execute("ALTER TABLE api_translation CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
            cursor.execute("ALTER TABLE api_sitesetting CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
            cursor.execute("ALTER TABLE api_customredirect CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")

def rollback_utf8mb4(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Revert tables
            cursor.execute("ALTER TABLE api_article CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;")
            cursor.execute("ALTER TABLE api_service CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;")
            cursor.execute("ALTER TABLE api_translation CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;")
            cursor.execute("ALTER TABLE api_sitesetting CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;")
            cursor.execute("ALTER TABLE api_customredirect CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_article_id_alter_customredirect_id_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_tables_to_utf8mb4, rollback_utf8mb4),
    ]
