# Generated by Django 6.0.5 on 2026-05-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_faqs_alter_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list, help_text='Enter a JSON list of strings, e.g., ["Item 1", "Item 2"]'),
        ),
        migrations.AddField(
            model_name='service',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='Enter a list of conditions, e.g., [{"id": 1, "title": "Back and neck pain", "description": "...", "icon": "<svg>..."}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='tag_badges',
            field=models.JSONField(blank=True, default=list, help_text='Enter a JSON list of strings, e.g., ["Badge 1", "Badge 2"]'),
        ),
    ]
