# Generated by Django 6.0.5 on 2026-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_service_checklist_items_service_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='checklist_image',
            field=models.ImageField(blank=True, help_text='Optional: Upload an illustration/image to replace the default therapist SVG', null=True, upload_to='services/illustrations/'),
        ),
        migrations.AddField(
            model_name='service',
            name='checklist_title',
            field=models.CharField(blank=True, help_text='Optional: Customize the checklist section heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='conditions_title',
            field=models.CharField(blank=True, help_text='Optional: Customize the conditions section heading', max_length=255, null=True),
        ),
    ]
