# Generated by Django 6.0.5 on 2026-05-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_service_checklist_image_service_checklist_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='activity', help_text='Lucide icon name', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='Enter a JSON list, e.g., ["Feature 1", "Feature 2"]'),
        ),
    ]
