# Generated by Django 6.0.5 on 2026-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_service_icon_alter_service_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Upload the gallery image', upload_to='gallery/')),
                ('category', models.CharField(choices=[('Clinic', 'Clinic'), ('Surgery', 'Surgery'), ('Consultation', 'Consultation'), ('Awards', 'Awards'), ('Conference', 'Conference'), ('About', 'About')], default='Clinic', max_length=50)),
                ('span', models.CharField(default='col-span-1 row-span-1', help_text='Grid span layout, e.g. col-span-1 row-span-1, col-span-2 row-span-2', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (ascending)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
