# Generated by Django 5.1.15 on 2026-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sitesetting_hero_video_alter_article_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload the main hero section video', upload_to='videos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Video',
                'verbose_name_plural': 'Hero Video',
            },
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_video',
        ),
    ]
