# Generated by Django 5.1.15 on 2026-06-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_herovideo_remove_sitesetting_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about_description',
            field=models.TextField(blank=True, help_text='Optional: Content for the dynamic about section', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='about_title',
            field=models.CharField(blank=True, help_text='Optional: Heading for the dynamic about section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='commonly_treated',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of categories, e.g., [{"title": "Upper Limb", "icon": "PlusSquare", "items": ["Item 1", "Item 2"]}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='commonly_treated_description',
            field=models.TextField(blank=True, help_text='Optional: Subtext for commonly treated section', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='commonly_treated_title',
            field=models.CharField(blank=True, help_text='Optional: Heading for commonly treated section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='who_needs_description',
            field=models.TextField(blank=True, help_text='Optional: Subtext/description for indications section', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='who_needs_items',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of strings, e.g., ["Symptom 1", "Symptom 2"]'),
        ),
        migrations.AddField(
            model_name='service',
            name='who_needs_title',
            field=models.CharField(blank=True, help_text='Optional: Heading for indications section', max_length=255, null=True),
        ),
    ]
