# Generated by Django 6.0.6 on 2026-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_service_about_description_service_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='highlight_badge',
            field=models.CharField(blank=True, help_text="e.g. 'Expertise & Precision'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_checklist_items',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of strings for highlight checklist'),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_checklist_title',
            field=models.CharField(blank=True, help_text="e.g. 'Successful knee replacement requires:'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_description',
            field=models.TextField(blank=True, help_text='Description under highlight title', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_doctor_badges',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of badges, e.g., ["UK-TRAINED", "FRCS"]'),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_doctor_description',
            field=models.TextField(blank=True, help_text='Doctor biography snippet', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/doctors/'),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_doctor_name',
            field=models.CharField(blank=True, help_text="e.g. 'Dr Ulhas Sonar'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_doctor_role',
            field=models.CharField(blank=True, help_text="e.g. 'Consultant Orthopedic Surgeon'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_title',
            field=models.CharField(blank=True, help_text="e.g. 'Why Choose Dr Ulhas Sonar...'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customredirect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
