# Generated by Django 6.0.6 on 2026-06-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_service_highlight_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='journey_description',
            field=models.TextField(blank=True, help_text='Subtext for the journey section', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='journey_is_active',
            field=models.BooleanField(default=False, help_text='Enable the journey step-by-step section for this service'),
        ),
        migrations.AddField(
            model_name='service',
            name='journey_steps',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of steps, e.g., [{"number": "01", "title": "Assessment", "description": "...", "icon": "ClipboardList", "color": "text-blue-500", "gradient": "from-blue-500/10 to-blue-500/0", "shadowHover": "hover:shadow-blue-500/20", "borderHover": "group-hover:border-blue-200"}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='journey_title',
            field=models.CharField(blank=True, help_text="e.g. 'Your Robotic Knee Replacement Journey'", max_length=255, null=True),
        ),
    ]
