# Generated by Django 6.0.6 on 2026-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_service_journey_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_services',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of sub-services, e.g., [{"title": "Sub", "slug": "sub"}]'),
        ),
    ]
