# Generated by Django 6.0.6 on 2026-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_service_sub_services_subservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='journey_steps',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of steps, e.g., [{"number": "01", "title": "Assessment", "description": "..."}]'),
        ),
    ]
