# Generated by Django 6.0.6 on 2026-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_service_journey_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
