# Generated by Django 6.0.6 on 2026-07-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_subservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cta_button_link',
            field=models.CharField(blank=True, help_text="e.g. '/contact'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_button_text',
            field=models.CharField(blank=True, help_text="e.g. 'Book Appointment Now'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_subtitle',
            field=models.CharField(blank=True, help_text="e.g. 'Get expert orthopedic care today.'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cta_title',
            field=models.CharField(blank=True, help_text="e.g. 'Struggling with Joint or Back Pain?'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_button_link',
            field=models.CharField(blank=True, default='/contact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Book Appointment Now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_subtitle',
            field=models.CharField(blank=True, default='Get expert orthopedic care today.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_title',
            field=models.CharField(blank=True, default='Struggling with Joint or Back Pain?', max_length=255, null=True),
        ),
    ]
