# Generated by Django 6.0.6 on 2026-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_service_cta_button_link_service_cta_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('knee', 'Knee Replacement'), ('acl', 'ACL or Meniscus Surgery'), ('hipShoulder', 'Hip or Shoulder Surgery'), ('fracture', 'Fracture or Trauma Treatment'), ('general', 'General Orthopedic Second Opinion')], default='knee', max_length=50)),
                ('title', models.CharField(help_text='Title, e.g., Second Opinion Before Knee Replacement', max_length=255)),
                ('paragraph_1', models.TextField(help_text='First paragraph: what decisions are based on')),
                ('paragraph_2', models.TextField(help_text='Second paragraph: what a second opinion clarifies')),
                ('order', models.IntegerField(default=0, help_text='Display order (ascending)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Second Opinion',
                'verbose_name_plural': 'Second Opinions',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
