# Generated by Django 6.0.6 on 2026-07-25 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_secondopinion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondopinion',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Specialized Orthopedic Care', 'verbose_name_plural': 'Specialized Orthopedic Care (Second Opinions)'},
        ),
        migrations.AddField(
            model_name='secondopinion',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Associated Service (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_opinions', to='api.service'),
        ),
    ]
