# Generated by Django 6.0.6 on 2026-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_secondopinion_options_secondopinion_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='second_opinion_badge',
            field=models.CharField(blank=True, default='Specialized Orthopedic Care', help_text='Badge text above heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_opinion_description',
            field=models.TextField(blank=True, help_text='Subtitle description for second opinions section', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='second_opinion_is_active',
            field=models.BooleanField(default=True, help_text='Enable the Second Opinion / Specialized Orthopedic Care section'),
        ),
        migrations.AddField(
            model_name='service',
            name='second_opinion_title',
            field=models.CharField(blank=True, default='Second Opinion Services', help_text='Heading title for second opinions section', max_length=255, null=True),
        ),
    ]
