# Generated by Django 6.0.6 on 2026-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_service_second_opinion_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='second_opinion_is_active',
            field=models.BooleanField(default=False, help_text='Enable the Second Opinion / Specialized Orthopedic Care section for this service'),
        ),
    ]
