# Generated by Django on 2026-07-26

from django.db import migrations

def disable_second_opinion(apps, schema_editor):
    Service = apps.get_model('api', 'Service')
    Service.objects.filter(second_opinion_is_active=True).update(second_opinion_is_active=False)

def reverse_disable_second_opinion(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_service_second_opinion_is_active'),
    ]

    operations = [
        migrations.RunPython(disable_second_opinion, reverse_code=reverse_disable_second_opinion),
    ]
