# Generated by Django 5.2.17 on 2026-08-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_article_id_alter_customredirect_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of FAQs, e.g. [{"question": "...", "answer": "..."}]'),
        ),
    ]
