# Generated by Django 5.2.17 on 2026-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_article_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='follow_links',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this sub service page'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='index_page',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this sub service page'),
        ),
    ]
