# Generated by Django 5.2.17 on 2026-08-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_subservice_follow_links_subservice_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sitemap_xml',
            field=models.TextField(blank=True, help_text='Custom sitemap.xml content. Leave empty to automatically generate dynamic sitemap from articles & services.', null=True),
        ),
    ]
