# Generated by Django 5.2.17 on 2026-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_sitesetting_sitemap_xml'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='FAQ question', max_length=500)),
                ('answer', models.TextField(help_text='FAQ answer')),
                ('order', models.IntegerField(default=0, help_text='Display order (ascending)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is visible on the home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home FAQ',
                'verbose_name_plural': 'Home FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
