# Generated by Django 5.2.17 on 2026-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_homefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's absolute URL", max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('MedicalBusiness', 'Medical Business / Local Business'), ('FAQPage', 'FAQ Page'), ('BreadcrumbList', 'Breadcrumbs'), ('None', 'Custom / None')], default='None', max_length=50)),
                ('schema_markup', models.JSONField(blank=True, help_text='JSON-LD schema markup', null=True)),
                ('index_page', models.BooleanField(default=True, help_text='Should search engines index this page?')),
                ('follow_links', models.BooleanField(default=True, help_text='Should search engines follow links on this page?')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the main image', max_length=255, null=True)),
                ('h1_title', models.CharField(blank=True, help_text='Optional: Override the default H1 title', max_length=255, null=True)),
                ('title', models.CharField(default='Home Page', max_length=255)),
                ('faq_badge', models.CharField(blank=True, default='Help Center', max_length=255, null=True)),
                ('faq_title', models.CharField(blank=True, default='Asked Frequently Questions', max_length=255, null=True)),
                ('faq_description', models.TextField(blank=True, default='Common questions about our care, robotic surgery, and orthopedic treatments in Dubai.', null=True)),
                ('faqs', models.JSONField(blank=True, default=list, help_text='List of FAQs, e.g. [{"question": "...", "answer": "..."}]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.DeleteModel(
            name='HomeFAQ',
        ),
    ]
