# Generated by Django 5.2.17 on 2026-09-06 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_homepage_delete_homefaq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-date']},
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the article is published / scheduled to appear on the website'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('scheduled', 'Scheduled'), ('draft', 'Draft')], db_index=True, default='published', help_text='Status of the article', max_length=20),
        ),
    ]
