# Generated by Django 5.2.17 on 2026-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_article_options_article_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportingInjurySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='EXPERT SPORTS ORTHOPEDIC CARE', help_text='Badge text above the main heading', max_length=255)),
                ('title', models.CharField(default='Sports Injury', help_text='First part of heading', max_length=255)),
                ('title_highlight', models.CharField(default='Clinic', help_text='Highlighted gradient part of heading', max_length=255)),
                ('title_end', models.CharField(blank=True, default=' Dubai', help_text='Trailing part of heading', max_length=255)),
                ('description', models.TextField(default='Specialized, minimally invasive treatments and accelerated recovery programs designed for athletes and active individuals of all performance levels.', help_text='Introductory text describing the sports injury clinic')),
                ('video_embed_url', models.CharField(blank=True, default='https://www.instagram.com/reel/DTijxQ3krcw/embed/?autoplay=1', help_text='Instagram Reel / YouTube / Embed iframe URL', max_length=500)),
                ('video_file', models.FileField(blank=True, help_text='Optional: Upload an MP4 video file instead of embed URL', null=True, upload_to='sports_injury/')),
                ('dashboard_label', models.CharField(default='DR. ULHAS CLINICAL REEL', help_text='Header badge text above the video card', max_length=255)),
                ('learn_more_heading', models.CharField(default='COMPREHENSIVE ATHLETIC CARE & RETURN-TO-PLAY', help_text='Heading for the treatment features list', max_length=255)),
                ('items', models.JSONField(blank=True, default=list, help_text='List of items with title and desc, e.g. [{"title": "High-Performance Athlete Recovery", "desc": "..."}, ...]')),
                ('cta_text', models.CharField(blank=True, default='Book Sports Consultation', max_length=255, null=True)),
                ('cta_link', models.CharField(blank=True, default='/contact', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sports Injury Clinic Section',
                'verbose_name_plural': 'Sports Injury Clinic Section',
            },
        ),
    ]
