# Generated by Django 5.2.17 on 2026-09-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_sportinginjurysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sports_badge',
            field=models.CharField(blank=True, default='EXPERT SPORTS ORTHOPEDIC CARE', help_text='Badge text above heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_cta_link',
            field=models.CharField(blank=True, default='/contact', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_cta_text',
            field=models.CharField(blank=True, default='Book Sports Consultation', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_dashboard_label',
            field=models.CharField(blank=True, default='DR. ULHAS CLINICAL REEL', help_text='Header badge text above video card', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_description',
            field=models.TextField(blank=True, default='Specialized, minimally invasive treatments and accelerated recovery programs designed for athletes and active individuals of all performance levels.', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_is_active',
            field=models.BooleanField(default=True, verbose_name='Enable Sports Injury Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_items',
            field=models.JSONField(blank=True, default=list, help_text='List of items with title and desc, e.g. [{"title": "High-Performance Athlete Recovery", "desc": "..."}, ...]'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_learn_more_heading',
            field=models.CharField(blank=True, default='COMPREHENSIVE ATHLETIC CARE & RETURN-TO-PLAY', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_title',
            field=models.CharField(blank=True, default='Sports Injury', help_text='First part of heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_title_end',
            field=models.CharField(blank=True, default=' Dubai', help_text='Trailing part of heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_title_highlight',
            field=models.CharField(blank=True, default='Clinic', help_text='Highlighted gradient part', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_video_embed_url',
            field=models.CharField(blank=True, default='https://www.instagram.com/reel/DTijxQ3krcw/embed/?autoplay=1', help_text='Instagram Reel / YouTube / Embed URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sports_video_file',
            field=models.FileField(blank=True, help_text='Optional: Upload an MP4 video file instead of embed URL', null=True, upload_to='sports_injury/'),
        ),
    ]
