# Generated by Django 5.2.17 on 2026-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_homepage_sports_badge_homepage_sports_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='trust_badge',
            field=models.CharField(blank=True, default='PATIENT-FOCUSED EXCELLENCE', help_text='Badge text above heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_cards',
            field=models.JSONField(blank=True, default=list, help_text='List of trust cards, e.g. [{"id": "01", "icon": "Award", "title": "Expert Care", "description": "...", "badge": "14+ Yrs Experience"}]'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_description',
            field=models.TextField(blank=True, default='Combining global surgical experience with cutting-edge technology and a compassionate, individualized recovery approach.', help_text='Subtext under the heading', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_is_active',
            field=models.BooleanField(default=True, verbose_name='Enable Why Patients Trust Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_title',
            field=models.CharField(blank=True, default='Why Patients Trust', help_text='First part of heading', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='trust_title_highlight',
            field=models.CharField(blank=True, default='Dr. Ulhas Sonar', help_text='Highlighted gradient part of heading', max_length=255, null=True),
        ),
    ]
