# Generated by Django 5.2.17 on 2026-09-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_homepage_trust_badge_homepage_trust_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='faq_badge',
            field=models.CharField(blank=True, default='Help Center', help_text='Small badge text above the FAQ title', max_length=255, null=True, verbose_name='FAQ Badge'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faq_description',
            field=models.TextField(blank=True, default='Common questions about our care, robotic surgery, and orthopedic treatments in Pune, India.', help_text='Subtitle or description text displayed directly below the FAQ title', null=True, verbose_name='FAQ Subtitle / Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faq_title',
            field=models.CharField(blank=True, default='Frequently Asked Questions', help_text='Main heading for the FAQ section', max_length=255, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of FAQs, e.g. [{"question": "...", "answer": "..."}]', verbose_name='FAQ Items (Q&A)'),
        ),
    ]
