# Generated by Django 5.2.17 on 2026-09-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_homepage_faq_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's absolute URL", max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('schema_type', models.CharField(choices=[('Article', 'Article'), ('MedicalBusiness', 'Medical Business / Local Business'), ('FAQPage', 'FAQ Page'), ('BreadcrumbList', 'Breadcrumbs'), ('None', 'Custom / None')], default='None', max_length=50)),
                ('schema_markup', models.JSONField(blank=True, help_text='JSON-LD schema markup', null=True)),
                ('index_page', models.BooleanField(default=True, help_text='Should search engines index this page?')),
                ('follow_links', models.BooleanField(default=True, help_text='Should search engines follow links on this page?')),
                ('image_alt_text', models.CharField(blank=True, help_text='Alt text for the main image', max_length=255, null=True)),
                ('h1_title', models.CharField(blank=True, help_text='Optional: Override the default H1 title', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='Services Page', max_length=255)),
                ('faq_badge', models.CharField(blank=True, default='Help Center', help_text='Small badge text above the FAQ title', max_length=255, null=True, verbose_name='FAQ Badge')),
                ('faq_title', models.CharField(blank=True, default='Services FAQ', help_text='Main heading for the Services page FAQ section', max_length=255, null=True, verbose_name='FAQ Title')),
                ('faq_description', models.TextField(blank=True, default='Common questions about our orthopedic procedures and specialized care plans in Pune, India.', help_text='Subtitle or description text displayed directly below the FAQ title', null=True, verbose_name='FAQ Subtitle / Description')),
                ('faqs', models.JSONField(blank=True, default=list, help_text='List of FAQs, e.g. [{"question": "...", "answer": "..."}]', verbose_name='FAQ Items (Q&A)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Page',
                'verbose_name_plural': 'Services Page',
            },
        ),
    ]
