# Generated by Django 5.2.17 on 2026-09-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_servicespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq_description',
            field=models.TextField(blank=True, help_text='Subtitle or description text displayed below the FAQ title for this service', null=True, verbose_name='FAQ Subtitle / Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_title',
            field=models.CharField(blank=True, default='Frequently Asked Questions', help_text='Heading for the FAQ section of this service', max_length=255, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='Enter a list of FAQs, e.g. [{"question": "...", "answer": "..."}]', verbose_name='FAQ Items (Q&A)'),
        ),
    ]
