# Generated by Django 5.2.17 on 2026-09-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_service_faq_description_service_faq_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='faq_badge',
            field=models.CharField(blank=True, default='Frequently asked questions', help_text='Small badge text above the FAQ title', max_length=255, null=True, verbose_name='FAQ Badge'),
        ),
    ]
