# Generated by Django 5.2.17 on 2026-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_service_faq_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_badge',
            field=models.CharField(blank=True, default='UK-TRAINED | FRCS (ENG) | EBOT | ROBOTIC FELLOWSHIP', help_text='Top pill badge text above the main headline', max_length=255, null=True, verbose_name='Hero Qualifications Badge'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_book_btn_link',
            field=models.CharField(blank=True, default='/contact', max_length=255, null=True, verbose_name='Primary Button Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_book_btn_text',
            field=models.CharField(blank=True, default='Book Consultation', max_length=255, null=True, verbose_name='Primary Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, default='UK & Europe trained Consultant Orthopedic Surgeon with 15+ years of clinical excellence in robotic joint replacement, advanced arthroscopy, sports injury rehabilitation, and deformity correction.', help_text='Introductory description paragraph', null=True, verbose_name='Hero Description / Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_doctor_name',
            field=models.CharField(blank=True, default='Dr. Ulhas Sonar', max_length=255, null=True, verbose_name='Doctor Card Name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_doctor_role',
            field=models.CharField(blank=True, default='Consultant Orthopedic Surgeon', max_length=255, null=True, verbose_name='Doctor Card Role / Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline_1',
            field=models.CharField(blank=True, default='Patient Centric, Evidence', help_text='First line of main heading', max_length=255, null=True, verbose_name='Headline Line 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline_2',
            field=models.CharField(blank=True, default='Based & Individualised', help_text='Second line of main heading', max_length=255, null=True, verbose_name='Headline Line 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline_3',
            field=models.CharField(blank=True, default='Orthopedic Care', help_text='Third line with gradient accent', max_length=255, null=True, verbose_name='Headline Line 3 (Gradient Highlight)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_is_active',
            field=models.BooleanField(default=True, verbose_name='Enable Hero Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_report_btn_link',
            field=models.CharField(blank=True, default='/report-access', max_length=255, null=True, verbose_name='Report Access Button Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_report_btn_text',
            field=models.CharField(blank=True, default='Report Access', max_length=255, null=True, verbose_name='Report Access Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_services_btn_link',
            field=models.CharField(blank=True, default='/services', max_length=255, null=True, verbose_name='Explore Services Button Link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_services_btn_text',
            field=models.CharField(blank=True, default='Explore Services', max_length=255, null=True, verbose_name='Explore Services Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_stats',
            field=models.JSONField(blank=True, default=list, help_text='List of stats, e.g. [{"value": "15", "suffix": "+", "label": "Years Clinical Experience"}, ...]', verbose_name='Hero Stats Counter Items'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 video file for the hero 3D card', null=True, upload_to='videos/', verbose_name='Hero Video File'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_video_url',
            field=models.CharField(blank=True, help_text='Optional external/direct video link', max_length=500, null=True, verbose_name='Hero Video URL'),
        ),
    ]
