# Generated by Django 6.0.5 on 2026-06-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(default='files', upload_to='reports/'),
            preserve_default=False,
        ),
    ]
