# Generated by Django 6.0.5 on 2026-06-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_report_report_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportaccessotp',
            unique_together={('email', 'report')},
        ),
    ]
