# Generated by Django 6.0.5 on 2026-06-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_reportaccessotp_unique_together'),
    ]

    operations = [
    ]
