# Generated by Django 6.0.5 on 2026-06-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_remove_duplicate_otps'),
        ('Report', '0004_remove_duplicate_otps'),
    ]

    operations = [
    ]
