# Generated by Django 6.0.5 on 2026-06-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_merge_20260609_1522'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportaccessotp',
            unique_together=set(),
        ),
    ]
