"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from decouple import config

#fix here

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    "drulhasorthopedic.com",
    "www.drulhasorthopedic.com",
    "api.drulhasorthopedic.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.redirects',
    'django.contrib.sites',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'ckeditor',
    
    # Local apps

    'api',
    'Report',
]

SITE_ID = 1

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    'api.middleware.SEOMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.getenv('DJANGO_DB_ENGINE') or not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': config('DJANGO_DB_ENGINE', default='django.db.backends.mysql'),
            'NAME':  config('DJANGO_DB_NAME', default='drulhas_db'),
            'USER': config('DJANGO_DB_USER', default='root'),
            'PASSWORD': config('DJANGO_DB_PASSWORD', default='password'),
            'HOST': config('DJANGO_DB_HOST', default='localhost'),
            'PORT': config('DJANGO_DB_PORT', default='3306'),
            # 'OPTIONS': {
            #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            # },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://drulhasorthopedic.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://drulhasorthopedic.com",
    "https://www.drulhasorthopedic.com",
    "https://api.drulhasorthopedic.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# Celery Configuration
CELERY_BROKER_URL = 'memory://'
CELERY_TASK_ALWAYS_EAGER = True

# Production SEO & Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Unfold Admin Settings
# UNFOLD = {
#     "SITE_TITLE": "Dr. Ulhas Sonar Admin",
#     "SITE_HEADER": "Dr. Ulhas Sonar",
#     "SITE_URL": "/",
#     "SITE_ICON": "api/images/logo.png",
#     "DASHBOARD_CALLBACK": None,
#     "STYLES": [
#         lambda request: "/static/api/css/unfold_custom.css",
#     ],
#     "COLORS": {
#         "primary": {
#             "50": "240 249 255",
#             "100": "224 242 254",
#             "200": "186 230 253",
#             "300": "125 211 252",
#             "400": "56 189 248",
#             "500": "14 165 233",
#             "600": "2 132 199",
#             "700": "3 105 161",
#             "800": "7 89 133",
#             "900": "12 74 110",
#             "950": "8 47 73",
#         },
#     },
#     "SIDEBAR": {
#         "show_search": True,
#         "show_all_applications": True,
#         "navigation": [
#             {
#                 "title": "Navigation",
#                 "separator": True,
#                 "items": [
#                     {
#                         "title": "Dashboard",
#                         "icon": "dashboard",
#                         "link": "/admin/",
#                     },
#                 ],
#             },
#         ],
#     },
# }

JAZZMIN_SETTINGS = {
    "site_title": "Dr Ulhas Admin",
    "site_header": "Dr Ulhas Dashboard",
    "site_brand": "Ulhas System",
    "welcome_sign": "Welcome Admin",
    "show_sidebar": True,
    "navigation_expanded": True,
}
# Monkey patch for MariaDB 10.4 compatibility
try:
    from django.db.backends.base.base import BaseDatabaseWrapper
    BaseDatabaseWrapper.check_database_version_supported = lambda self: True
    from django.db.backends.mysql.features import DatabaseFeatures
    DatabaseFeatures.can_return_columns_from_insert = property(lambda self: False)
    DatabaseFeatures.can_return_rows_from_bulk_insert = property(lambda self: False)
except Exception:
    pass


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # explicitly set this — conflicts cause silent failures
EMAIL_HOST_USER = "contact@drulhasorthopedic.com"
EMAIL_HOST_PASSWORD = "tA6&>T&DpcZ"
DEFAULT_FROM_EMAIL = "contact@drulhasorthopedic.com"
EMAIL_ADMIN_USER = "admin@drulhasorthopedic.com"